// To update
// 1. delete everything after '='
// 2. cd to this folder
// 3. sed 's/"/\\"/g' test.html | sed 's/$/\\n"/g' | sed 's/^/"/g' >> homepage.c
// 4. echo ';' >> homepage.c
// 5. remove various test scaffolding
static const char* main_page_content = "<html><head>\n""<html><head>\n"
"<title>"CONFIG_LC_MDNS_INSTANCE" Control Panel</title>\n"
"<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\n"
"</head>\n"
"<body bgcolor=\"0x111111\" style=\"color: #BBBBEE;\">\n"
"<h1>"CONFIG_LC_MDNS_INSTANCE" Control Panel</h1>\n"
"<h2 id=\"current_time\">Current Local Time: ...</h2>\n"
"<h2>Actions</h2>\n"
"<p>Alarm:\n"
"<button id=\"alarm_snooze\">Snooze</button>\n"
"<button id=\"alarm_stop\">Stop</button></p>\n"
"<p>Sleep Timer: <button id=\"sleep_start\">Start</button> <button id=\"sleep_stop\">Stop</button></p>\n"
"<p>LEDs: <button id=\"run_pattern\">Run Selected Alarm LED Pattern</button></p>\n"
"<h2>Alarm Clock Settings</h2>\n"
"<p>Time: <select id=\"alarm_hour\"></select>:<select id=\"alarm_minute\"></select></p>\n"
"<p>Enabled: <select id=\"alarm_enabled\"></select></p>\n"
"<p>LED Pattern: <select id=\"alarm_led_pattern\"></select></p>\n"
"<p>Snooze Interval (min): <select id=\"alarm_snooze_interval_min\"></select></p>\n"
"<h2>Sleep Timer Settings</h2>\n"
"<p>Sleep Delay: <select id=\"sleep_delay_min\"></select>&nbsp;minutes from trigger to fade start</p>\n"
"<p>Sleep Fade Time: <select id=\"sleep_fade_time_min\"></select>&nbsp;minutes from fade start to full-off</p>\n"
"<h2>Save Settings</h2>\n"
"<p><button id=\"save\">Save</button></p>\n"
"<!-- positioned at end so DOM elements are already loaded -->\n"
"<script>\n"
"(async function() {\n"
"'use strict';\n"
"var settings_response = await fetch('/settings');\n"
"var settings = await settings_response.json();\n"
"var ranges = settings.ranges;\n"
"delete settings.ranges;\n"
"Object.keys(settings).forEach(function(setting_name) {\n"
"    // Find the tag\n"
"    var elem = document.getElementById(setting_name);\n"
"    if (elem === null) { console.error('element not found for setting '+setting_name); return; }\n"
"    // Populate the tag with possible values\n"
"    var range = ranges[setting_name]\n"
"    range.forEach(function(val){\n"
"        var option_elem = document.createElement('option');\n"
"        option_elem.setAttribute('value', ''+val);\n"
"        option_elem.innerText = ''+val;\n"
"        elem.appendChild(option_elem);\n"
"    });\n"
"    // Set the value\n"
"    elem.selectedIndex = range.indexOf(settings[setting_name]);\n"
"    // Special-case the string-based field alarm_led_pattern\n"
"    if (setting_name === 'alarm_led_pattern') { elem.selectedIndex = settings[setting_name]; }\n"
"});\n"
"// Begin action handler logic\n"
"document.getElementById('save').onclick = async function post_settings() {\n"
"    var new_settings = {};\n"
"    Object.keys(settings).forEach(function(setting_name) {\n"
"        var elem = document.getElementById(setting_name);\n"
"        if (elem === null) { console.error('element not found for setting '+setting_name); return; }\n"
"        var val_array = ranges[setting_name];\n"
"        new_settings[setting_name] = ranges[setting_name][elem.selectedIndex];\n"
"        // Special-case the string-based field alarm_led_pattern\n"
"        if (setting_name === 'alarm_led_pattern') { new_settings[setting_name] = elem.selectedIndex; }\n"
"    });\n"
"    console.log(JSON.stringify(new_settings));\n"
"    await fetch('/settings', {\n"
"        method: 'POST',\n"
"        body: JSON.stringify(new_settings),\n"
"        headers: { 'Content-Type': 'application/json' },\n"
"    });\n"
"}\n"
"setInterval(async function() {\n"
"    var time_req = await fetch('/time');\n"
"    var time_string = await time_req.text();\n"
"    document.getElementById('current_time').innerText = 'Current Local Time: '+time_string;\n"
"}, 1000);\n"
"document.getElementById('alarm_snooze').onclick = async function alarm_snooze() {\n"
"    await fetch('/command?alarm_snooze=1');\n"
"};\n"
"document.getElementById('alarm_stop').onclick = async function alarm_stop() {\n"
"    await fetch('/command?alarm_stop=1');\n"
"};\n"
"document.getElementById('sleep_start').onclick = async function sleep_start() {\n"
"    await fetch('/command?sleep_start=1');\n"
"};\n"
"document.getElementById('sleep_stop').onclick = async function sleep_stop() {\n"
"    await fetch('/command?sleep_stop=1');\n"
"};\n"
"document.getElementById('run_pattern').onclick = async function run_pattern() {\n"
"    await fetch('/command?run_pattern='+(document.getElementById('alarm_led_pattern').selectedIndex));\n"
"};\n"
"}());\n"
"// ESP32 light clock project\n"
"// Author: Jon Kunkee (jonathan.kunkee@gmail.com)\n"
"// Sure, it's 0BSD-licensed, but if you leave this in then I shall be most amused.\n"
"</script>\n"
"</body></html>\n"
;
