static const char* main_page_content =
"<html><head>\n"
"<title>"CONFIG_LC_MDNS_INSTANCE" Control Panel</title>\n"
"<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\n"
"</head>\n"
"<body bgcolor=\"0x111111\" style=\"color: #BBBBEE;\">\n"
"<h1>"CONFIG_LC_MDNS_INSTANCE" Control Panel</h1>\n"
"<h2>Actions</h2>\n"
"<p>Alarm:\n"
"<button id=\"alarm_snooze\">Snooze</button>\n"
"<button id=\"alarm_stop\">Stop</button></p>\n"
"<p>Sleep Timer: <button id=\"sleep_start\">Start</button> <button id=\"sleep_stop\">Stop</button></p>\n"
"<p>LEDs: <button>Run Selected Alarm LED Pattern</button></p>\n"
"<h2>Alarm Clock Settings</h2>\n"
"<p>Time: <select id=\"alarm_hour\"></select>:<select id=\"alarm_minute\"></select></p>\n"
"<p>Enabled: <select id=\"alarm_enabled\"></select></p>\n"
"<p>LED Pattern: <select id=\"alarm_led_pattern\"></select></p>\n"
"<p>Snooze Interval (min): <select id=\"alarm_snooze_interval_min\"></select></p>\n"
"<h2>Sleep Timer Settings</h2>\n"
"<p>Sleep Delay: <select id=\"sleep_delay_min\"></select>&nbsp;minutes from trigger to fade start</p>\n"
"<p>Sleep Fade Time: <select id=\"sleep_fade_time_min\"></select>&nbsp;minutes from fade start to full-off</p>\n"
"<h2>Save Settings</h2>\n"
"<p><button id=\"save\">Save</button></p>\n"
"<!-- positioned at end so DOM elements are already loaded -->\n"
"<script>\n"
"(async function() {\n"
"\"use strict\";\n"
"var settings_response = await fetch('/settings');\n"
"var settings = await settings_response.json();\n"
"Object.keys(settings).forEach(function(setting_name) {\n"
"    // Find the tag\n"
"    var elem = document.getElementById(setting_name);\n"
"    if (elem === null) { return; }\n"
"    // Populate the tag with possible values\n"
"    var range = settings.ranges[setting_name]\n"
"    range.forEach(function(val){\n"
"        var option_elem = document.createElement('option');\n"
"        option_elem.setAttribute('value', ''+val);\n"
"        option_elem.innerText = ''+val;\n"
"        elem.appendChild(option_elem);\n"
"    });\n"
"    // Set the value\n"
"    elem.selectedIndex = range.indexOf(settings[setting_name]);\n"
"});\n"
"function gather_settings() {\n"
"    var new_settings = {};\n"
"    Object.keys(settings).forEach(function(setting_name) {\n"
"        var elem = document.getElementById(setting_name);\n"
"        if (elem === null) { return; }\n"
"        var val_array = settings.ranges[setting_name];\n"
"        new_settings[setting_name] = settings.ranges[setting_name][elem.selectedIndex];\n"
"    });\n"
"    return new_settings;\n"
"}\n"
"async function post_settings() {\n"
"    await fetch('/settings', {\n"
"        method: 'POST',\n"
"        body: JSON.stringify(gather_settings()),\n"
"        headers: { 'Content-Type': 'application/json' }\n"
"    });\n"
"}\n"
"document.getElementById(\"save\").onclick = post_settings;\n"
"}());\n"
"</script>\n"
"</body></html>\n"
;


